swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Eshop Item Controller API'
basePath: /items
tags:
  - name: Item
    description: Operations related to items
schemes:
  - http
paths:
  /findAllItems:
    get:
      tags:
        - Item
      summary: Get all items
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
  /addNewItem:
    post:
      tags:
        - Item
      summary: Create a new item
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: item
          description: Item object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Item'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Item'
        '400':
          description: Bad Request
  /updateItem/{id}:
    put:
      tags:
        - Item
      summary: Update an item by ID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID of the item that needs to be updated
          required: true
          type: integer
        - in: body
          name: item
          description: Item object that needs to be updated
          required: true
          schema:
            $ref: '#/definitions/Item'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Item'
        '400':
          description: Bad Request
  /deleteItem/{itemId}:
    delete:
      tags:
        - Item
      summary: Delete an item by ID
      produces:
        - application/json
      parameters:
        - in: path
          name: itemId
          description: ID of the item that needs to be deleted
          required: true
          type: integer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
